# name: deploy-aws-lambda
# on:
#   push:
#     branches:
#       - main
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [10.x]
#     steps:
#       - uses: actions/checkout@master
#       - name: Install Serverless Framework
#         run: npm install -g serverless@1.71.3

#       - name: Serverless AWS authentication
#         run:
#           sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY
#           }} --secret ${{ secrets.AWS_SECRET_KEY }}

#       - name: Install NPM dependencies
#         run: npm install

#       - name: Deploy Lambda functions
#         run: sls deploy -s staging
